name: "build"

on:
  push:
    branches: "**"
    tags-ignore: ["**"]
  pull_request:
    branches: "**"

jobs:
  call-build:
    uses: KyoriPowered/.github/.github/workflows/shared-ci.yaml@trunk
    secrets: inherit
    with:
      runtime_version: 17
